import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {homedir} from 'node:os';
const base=process.argv[2]||'http://127.0.0.1:18641';
const secrets=JSON.parse(await readFile(join(process.env.LOCALAPPDATA||homedir(),'PLVA','CloudWorkspace','secrets.json'),'utf8'));
assert.equal((await fetch(base+'/')).status,200);
assert.equal((await fetch(base+'/api/state')).status,401);
assert.equal((await fetch(base+'/bridge')).status,401);
const login=await fetch(base+'/auth/session',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({key:secrets.APP_ACCESS_KEY})});
assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert.ok(cookie.includes('HttpOnly'));assert.ok(cookie.includes('Secure'));assert.ok(cookie.includes('SameSite=Strict'));
const headers={cookie:cookie.split(';')[0],origin:base,'content-type':'application/json'};
assert.equal((await fetch(base+'/api/stop',{method:'POST',headers:{...headers,origin:'https://unrelated.example'},body:'{}'})).status,403);
const connection=await (await fetch(base+'/api/connection',{headers})).json();assert.equal(typeof connection.connected,'boolean');
assert.equal((await fetch(base+'/api/config',{method:'POST',headers,body:'{}'})).status,404);
assert.equal((await fetch(base+'/api/run',{method:'POST',headers,body:JSON.stringify({mode:'rehearsal',source:'fixture',task:'test'})})).status,400);
const create=await fetch(base+'/api/skills',{method:'POST',headers,body:JSON.stringify({name:'Integration check',instructions:'Inspect the current page, use the new inputs, and verify its heading.'})});assert.equal(create.status,201);const {skill}=await create.json();
const listing=await (await fetch(base+'/api/skills',{headers})).json();assert.ok(listing.skills.some(item=>item.id===skill.id));
assert.equal((await fetch(base+'/api/skills/'+skill.id,{method:'DELETE',headers})).status,200);
const clean=await (await fetch(base+'/api/skills',{headers})).json();assert.ok(!clean.skills.some(item=>item.id===skill.id));
assert.equal((await fetch(base+'/auth/logout',{method:'POST',headers,body:'{}'})).status,200);
console.log('Verified hosted app assets, owner authentication, CSRF checks, restricted API routes, computer connection status, durable procedure create/read/delete, and logout.');
